name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - "doc/**"
      - README.md

defaults:
  run:
    shell: bash

env:
  HOMEBREW_NO_AUTO_UPDATE: 1

jobs:

  build:
    strategy:
      matrix:
        os: [
          macos-latest,
          windows-latest,
          ubuntu-latest,
        ]
        python-version: ['3.10']
        dependencies: [full]
        tests-type: [unit]
        include:
          - os: ubuntu-latest
            python-version: 3.7
            dependencies: minimal
            tests-type: unit

    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    - uses: s-weigand/setup-conda@v1
      if: matrix.os == 'windows-latest'
      with:
        update-conda: true
        conda-channels: conda-forge
        activate-conda: true
        python-version: ${{matrix.python-version}}
    - name: Install dependencies and yt
      shell: bash
      env:
        dependencies: ${{ matrix.dependencies }}
      run: source ./tests/ci_install.sh
    - name: Run Tests
      env:
        testsuite: ${{ matrix.tests-type }}
      run: pytest
